app:
  mode: development # or production
  host: 0.0.0.0
  port: 8080

postgres:
  host: localhost
  port: 13579
  username: YOUR_USERNAME_HERE
  password: YOUR_PASSWORD_HERE
  database: setetes
  ssl_mode: verify-full
  ssl_cert: ./path/to/cert/server.crt
  max_open_connections: 25
  max_idle_connections: 5
  connection_max_lifetime: 10 # in minutes
  connection_max_idle_time: 15 # in minutes

redis:
  host: localhost
  port: 7692
  username: YOUR_USERNAME_HERE
  password: YOUR_PASSWORD_HERE
  database: 0
  max_retries: 5
  dial_timeout: 30 # in seconds
  read_timeout: 10 # in seconds
  write_timeout: 10 # in seconds
  ssl_cert: ./path/to/cert/server.crt
  pool_size: 30
  pool_timeout: 30 # in seconds
  min_idle_conns: 5
  max_idle_conns: 20
  conn_max_idle_time: 30 # in seconds
  conn_max_lifetime: 30 # in seconds

password:
  pepper: MIN_32_CHARACTERS
  argon2:
    memory: 12288 # in KiB
    iterations: 3
    parallelism: 1
    salt_length: 16 # min. 16 length
    key_length: 16 # min. 16 length

ed25519:
  private_key_path: ./path/to/pem/private.pem
  public_key_path: ./path/to/pem/public.pem
