app:
  mode: development # or production
  host: 0.0.0.0
  port: 8080

postgres:
  host: localhost
  port: 13579
  username: setetes_app
  password: YOUR_PASSWORD_HERE
  database: setetes
  sslmode: verify-full
  sslcert: ./path/to/cert/server.crt
  max_open_connections: 25
  max_idle_connections: 5
  connection_max_lifetime: 10 # in minutes
  connection_max_idle_time: 15 # in minutes

password:
  pepper: MIN_32_CHARACTERS
  argon2:
    memory: 12288 # in KiB
    iterations: 3
    parallelism: 1
    salt_length: 16 # min. 16 length
    key_length: 16 # min. 16 length

ed25519:
  private_key_path: ./path/to/pem/private.pem
  public_key_path: ./path/to/pem/public.pem
