name: setetes-dev

services:
  postgis:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgres.conf
    secrets:
      - sec-postgres
    ports:
      - "13579:13579"
    networks:
      - net-postgres
    healthcheck:
      test: pg_isready -d setetes -U healthcheck -p 13579
      interval: 30s
      timeout: 25s
      retries: 5
      start_period: 60s
    environment:
      POSTGRES_DB: setetes
      POSTGRES_USER: setetes_app
      POSTGRES_PASSWORD_FILE: /run/secrets/sec-postgres
      POSTGRES_INITDB_ARGS: "--data-checksums"
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    volumes:
      - ./docker/postgres/postgres.conf:/etc/postgresql/postgres.conf:ro
      - ./docker/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf:ro
      - ./docker/postgres/users.sql:/docker-entrypoint-initdb.d/00-users.sql:ro
      - ./docker/postgres/extension.sql:/docker-entrypoint-initdb.d/01-extension.sql:ro

  redis:
    image: redis:alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7692:7692"
    networks:
      - net-redis
    environment:
      TZ: Asia/Jakarta
    healthcheck:
      test: redis-cli -h localhost -p 7692 -a healthcheck_pass --user healthcheck PING
      interval: 30s
      timeout: 25s
      retries: 5
      start_period: 60s
    volumes:
      - vol-redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./docker/redis/users.acl:/etc/redis/users.acl:ro

  atlas:
    image: arigaio/atlas:latest-alpine
    restart: no
    depends_on:
      postgis:
        condition: service_healthy
    command: migrate apply --env docker
    working_dir: /app
    networks:
      - net-postgres
    secrets:
      - sec-postgres
    volumes:
      - vol-atlas:/app
      - ./atlas.hcl:/app/atlas.hcl:ro
      - ./migrations:/app/migrations

#  app:
#    build:
#      dockerfile: ./docker/Dockerfile
#    restart: unless-stopped
#    command: start --config config.yml
#    depends_on:
#      atlas:
#        condition: service_completed_successfully
#      redis:
#        condition: service_healthy
#    ports:
#      - "8080:8080"
#    networks:
#      - net-app
#      - net-postgres
#      - net-redis
#    healthcheck:
#      test: wget --spider -q http://127.0.0.1:8080/ping
#      interval: 30s
#      timeout: 25s
#      retries: 5
#      start_period: 60s
#    volumes:
#      - ./config.yml:/app/config.yml:ro
#      - ./ed25519-private.pem:/app/ed25519-private.pem:ro
#      - ./ed25519-public.pem:/app/ed25519-public.pem:ro

secrets:
  sec-postgres:
    file: ./docker/postgres/password

volumes:
  vol-redis:
    driver: local
  vol-atlas:
    driver: local

networks:
  net-app:
    driver: bridge
  net-postgres:
    driver: bridge
  net-redis:
    driver: bridge
